name: API Deploy

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      url:
        description: API URL
        value: ${{ jobs.build_and_deploy.outputs.url }}

defaults:
  run:
    working-directory: ./api

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GAR_LOCATION: asia-northeast1
      REPOSITORY: jellyfish-api
      SERVICE: jellyfish-api
      REGION: asia-northeast1
    outputs:
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}
          tags: type=sha,prefix=

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: api/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ steps.meta.outputs.tags }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
