name: API CI

on: [workflow_dispatch, workflow_call]

defaults:
  run:
    working-directory: ./api

jobs:
  unit_test:
    name: Unit test
    env:
      RUSTFLAGS: "-Dwarnings"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features
