name: API CI

on:
  workflow_dispatch:
  push:
    paths:
      - api/**

defaults:
  run:
    working-directory: ./api

jobs:
  unit_test:
    name: Unit test
    env:
      RUSTFLAGS: "-Dwarnings"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [unit_test]
    env:
      GAR_LOCATION: asia-northeast1
      REPOSITORY: jellyfish-api
      SERVICE: jellyfish-api

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}
          tags: type=sha,prefix=

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: api/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}