name: Jellyfish CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - web/**
      - api/**

jobs:
  web-ci:
    name: Web CI
    uses: ./.github/workflows/web-ci.yml

  api-ci:
    name: API CI
    uses: ./.github/workflows/api-ci.yml
  
  api-deploy:
    name: API Deploy
    needs: api-ci
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/api-deploy.yml

  web-deploy:
    name: Web Deploy
    needs: [web-ci, api-deploy]
    permissions:
      id-token: write
      contents: read
    uses: "./.github/workflows/web-deploy.yml"
    with:
      api-url: ${{ needs.api-deploy.outputs.url }}