name: Web CI

on:
  workflow_dispatch:
  push:
    paths:
      - web/**

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
