name: Web Deploy

on:
  workflow_dispatch:
    inputs:
      api-url:
        required: true
        type: string
  workflow_call:
    inputs:
      api-url:
        required: true
        type: string

defaults:
  run:
    working-directory: ./web

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GAR_LOCATION: asia-northeast1
      REPOSITORY: jellyfish-web
      SERVICE: jellyfish-web
      REGION: asia-northeast1

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.WIF_SERVICE_ACCOUNT }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}
          tags: type=sha,prefix=

      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: web/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ steps.meta.outputs.tags }}
          env_vars: |
            API_URL=${{ inputs.api-url }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
